#!/bin/sh
cd ~/.quran/audio

installed=`ls | head -n 1`
dir=${QURAN_RECITATION:-$installed}

if ! [ -d "$dir" ]; then
	echo "`basename $0`: invalid recitation ($dir)" >&2
	exit 1
fi

if command -v afplay > /dev/null; then
	player=afplay
else
	player="mpg123 -q"
	trap exit HUP INT TERM QUIT
fi

play() {
	if [ "$2" = 1 ]; then
		f=`printf '%s/%03d%03d.mp3' "$dir" "$1" 0`
		if ! [ -f "$f" ]; then
			if [ "$1" = 1 ]; then
				f=`printf '%s/audhubillah.mp3' "$dir"`
			else
				f=`printf '%s/bismillah.mp3' "$dir"`
			fi
		fi
		if [ -f "$f" ]; then $player "$f"; fi
	fi
	$player "`printf '%s/%03d%03d.mp3' "$dir" "$1" "$2"`"
}

while IFS= read line; do
	echo "$line"
	if echo "$line" | fgrep -q -- --; then
		pos=`echo "$line" | awk '{print $NF}'`
		surah=`echo $pos | cut -d : -f 1`
		verse=`echo $pos | cut -d : -f 2`
		play $surah $verse
	fi
done
